In [16]:
import pandas as pd
from sklearn.svm import SVC  
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.neural_network import MLPClassifier
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
#mnist=fetch_openml('mnist_784',version=1)

In [2]:
mnist.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [3]:
X,y=mnist["data"][:10000],mnist["target"][:10000]
print(X.shape)
print(y.shape)

(10000, 784)
(10000,)


In [4]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Columns: 784 entries, pixel1 to pixel784
dtypes: float64(784)
memory usage: 59.8 MB


In [5]:
X.head()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel781  pixel782  pixel783  pixel784  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 784 columns]

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
myscaler = StandardScaler()

In [8]:
StandardScaler(X)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass copy=      pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9999     0.0     0.0

StandardScaler(copy=      pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9998     0.0     0.0     0....
9996      0.0  ...       0.0       0.0       0.0       0.0       0.0   
9997      0.0  ...       0.0       0.0       0.0       0.0       0.0   
9998 

In [9]:
m1 = MLPClassifier(hidden_layer_sizes=(9, 12, 10, 15), activation='relu', solver='adam', max_iter=2000)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [11]:
# Feature scaling
scaler = StandardScaler()  
scaler.fit(X_train)
X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)

In [12]:
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

In [13]:
predictions = mlp.predict(X_test)

In [14]:
print(predictions)

['3' '2' '8' ... '9' '1' '5']


In [15]:
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))

[[177   0   2   1   0   1   3   1   3   2]
 [  0 214   3   2   0   1   1   0   3   1]
 [  1   1 157   7   6   0   4   4  11   0]
 [  2   3   4 175   0  10   0   2   6   3]
 [  1   2   1   2 181   2   4   6   0   6]
 [  1   2   0  12   2 132   2   2   7   3]
 [  0   0   3   0   6   4 200   2   1   0]
 [  0   0   3   1   3   1   0 180   5  12]
 [  3   2   8   4   2  15   4   1 166   0]
 [  1   1   0   4   9   1   0   7   2 170]]
              precision    recall  f1-score   support

           0       0.95      0.93      0.94       190
           1       0.95      0.95      0.95       225
           2       0.87      0.82      0.84       191
           3       0.84      0.85      0.85       205
           4       0.87      0.88      0.87       205
           5       0.79      0.81      0.80       163
           6       0.92      0.93      0.92       216
           7       0.88      0.88      0.88       205
           8       0.81      0.81      0.81       205
           9       0.86     

In [17]:
??mlp