In [155]:
import numpy as np
 
def PCA(X , num_components):
     
    #Step-1
    X_meaned = X - np.mean(X , axis = 0)
    print(X_meaned)
     
    #Step-2
    cov_mat = np.cov(X_meaned , rowvar = False)
    print(cov_mat)
     
    #Step-3
    eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)
    print(np.linalg.eigh(cov_mat))
#Step-4
    sorted_index = np.argsort(eigen_values)[::-1]
    sorted_eigenvalue = eigen_values[sorted_index]
    sorted_eigenvectors = eigen_vectors[sorted_index]
    print(eigen_vectors[1])
    
    subset=[]
    for i in range(num_components):
        subset.append(eigen_vectors[sorted_index[i]])
    arr = np.array(subset)
    #Step-5
#     eigenvector_subset = sorted_eigenvectors[:,1]
#     print("Eigen values",sorted_eigenvalue)
#     print ("Eigen vectors",eigen_vectors)
#     print( "Eigen sets",eigenvector_subset)
    #Step-6
    X_reduced = np.dot(arr , X_meaned.transpose() ).transpose()
     
    return X_reduced

In [159]:
X=[[3,2],[4,6],[5,4],[6,7],[7,8],[8,9]]

In [160]:
np.mean(X,axis=0)

array([5.5, 6. ])

In [161]:
PCA(X,1)

[[-2.5 -4. ]
 [-1.5  0. ]
 [-0.5 -2. ]
 [ 0.5  1. ]
 [ 1.5  2. ]
 [ 2.5  3. ]]
[[3.5 4.4]
 [4.4 6.8]]
(array([0.45079794, 9.84920206]), array([[-0.82192562,  0.56959484],
       [ 0.56959484,  0.82192562]]))
[0.56959484 0.82192562]


array([[-4.71168956],
       [-0.85439226],
       [-1.92864865],
       [ 1.10672304],
       [ 2.49824349],
       [ 3.88976395]])

In [82]:
X=[[2,4],[1,3],[0,1],[-1,.5]]

In [83]:
PCA(X,1)

[[ 1.5    1.875]
 [ 0.5    0.875]
 [-0.5   -1.125]
 [-1.5   -1.625]]
[[1.66666667 2.08333333]
 [2.08333333 2.72916667]]
(array([0.04791566, 4.34791768]), array([[-0.78964958,  0.6135581 ],
       [ 0.6135581 ,  0.78964958]]))
[0.6135581  0.78964958]
Eigen values [4.34791768 0.04791566]
Eigen vectors [[-0.78964958  0.6135581 ]
 [ 0.6135581   0.78964958]]
Eigen sets : [0.78964958 0.6135581 ]


array([ 2.33489581,  0.93168813, -1.08507765, -2.18150628])

In [44]:
X=[[4,11],[8,4],[13,5],[7,14]]

In [46]:
PCA(X,1)

[[-4.   2.5]
 [ 0.  -4.5]
 [ 5.  -3.5]
 [-1.   5.5]]
[[ 14. -11.]
 [-11.  23.]]
[ 6.61513568 30.38486432]
[[-0.55738997]
 [ 0.83025082]]


array([[ 4.30518692],
       [-3.73612869],
       [-5.69282771],
       [ 5.12376947]])

In [82]:
#[ 0.56959484 -0.82192562]
np.dot([[0.56959484],[-0.82192562]].transpose() , X_meaned.transpose() ).transpose()

AttributeError: 'list' object has no attribute 'transpose'

In [40]:
 eigen_vectors=[[-0.8219256,0.56959484],
                [ 0.56959484,0.82192562]]

In [41]:
sorted_index=[1,0]

In [42]:
eigen_vectors

[[-0.8219256, 0.56959484], [0.56959484, 0.82192562]]

In [53]:
eigen_vectors[:,y]

TypeError: list indices must be integers or slices, not tuple

In [112]:
a=np.empty(3)

In [113]:
X=[[90,60,90],[90,90,30],[60,60,60],[60,60,90],[30,30,30]]

array([  56.02457535,  786.38798335, 1137.5874413 ])