In [1]:
import pandas as pd
from sklearn.svm import SVC  
from sklearn.model_selection import train_test_split
from sklearn import metrics
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('iris.csv')

In [4]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [7]:
X=df.drop('species',axis=1)
y=df[['species']]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/5, random_state = 47)

In [21]:
from sklearn.model_selection import GridSearchCV

In [29]:
param_grid= {'decision_function_shape':['ovr','ovo'],
              'kernel': ['linear','rbf','poly','sigmoid']}

In [30]:
grid = GridSearchCV(SVC(), param_grid) 
grid.fit(X_train, y_train)
print(grid.best_params_)

{'decision_function_shape': 'ovr', 'kernel': 'linear'}


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using r

In [31]:
print(grid.best_params_)

{'decision_function_shape': 'ovr', 'kernel': 'linear'}


In [32]:
df = pd.DataFrame(grid.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.002993  8.920709e-04         0.001595        0.000790   
1       0.001795  3.988981e-04         0.001396        0.000488   
2       0.001995  1.784161e-07         0.001197        0.000399   
3       0.003391  7.984401e-04         0.001197        0.000399   
4       0.002002  6.419676e-04         0.001190        0.000403   
5       0.001795  3.988505e-04         0.001396        0.000488   
6       0.001396  4.885387e-04         0.001396        0.000489   
7       0.002404  5.019385e-04         0.001386        0.000498   

  param_decision_function_shape param_kernel  \
0                           ovr       linear   
1                           ovr          rbf   
2                           ovr         poly   
3                           ovr      sigmoid   
4                           ovo       linear   
5                           ovo          rbf   
6                           ovo         poly   
7                           ovo      sigmoid   

                                              params  split0_test_score  \
0  {'decision_function_shape': 'ovr', 'kernel': '...           0.958333   
1  {'decision_function_shape': 'ovr', 'kernel': '...           0.958333   
2  {'decision_function_shape': 'ovr', 'kernel': '...           1.000000   
3  {'decision_function_shape': 'ovr', 'kernel': '...           0.375000   
4  {'decision_function_shape': 'ovo', 'kernel': '...           0.958333   
5  {'decision_function_shape': 'ovo', 'kernel': '...           0.958333   
6  {'decision_function_shape': 'ovo', 'kernel': '...           1.000000   
7  {'decision_function_shape': 'ovo', 'kernel': '...           0.375000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.916667           1.000000           0.958333              1.000   
1           0.916667           0.958333           0.958333              1.000   
2           0.916667           0.958333           0.958333              1.000   
3           0.333333           0.333333           0.375000              0.375   
4           0.916667           1.000000           0.958333              1.000   
5           0.916667           0.958333           0.958333              1.000   
6           0.916667           0.958333           0.958333              1.000   
7           0.333333           0.333333           0.375000              0.375   

   mean_test_score  std_test_score  rank_test_score  
0         0.966667        0.031180                1  
1         0.958333        0.026352                5  
2         0.966667        0.031180                1  
3         0.358333        0.020412                7  
4         0.966667        0.031180                1  
5         0.958333        0.026352                5  
6         0.966667        0.031180                1  
7         0.358333        0.020412                7

In [35]:
df[['param_decision_function_shape','param_kernel','mean_test_score']]

param_decision_function_shape param_kernel  mean_test_score
0                           ovr       linear         0.966667
1                           ovr          rbf         0.958333
2                           ovr         poly         0.966667
3                           ovr      sigmoid         0.358333
4                           ovo       linear         0.966667
5                           ovo          rbf         0.958333
6                           ovo         poly         0.966667
7                           ovo      sigmoid         0.358333

In [40]:
decision_function_shape=['ovr','ovo']
kernel=['linear','rbf','poly','sigmoid']

for kval in kernel:
    for cval in decision_function_shape:
        clf = SVC(decision_function_shape =cval,kernel=kval) 
        clf.fit(X_train, y_train)
        y_pred = clf.predict(X_test)
        print('#'*50)
        print(cval," ",kval)
        confusion = metrics.confusion_matrix(y_test, y_pred)
        print(confusion)
        print('Accuracy Score on confusion_matrix: ' ,metrics.accuracy_score(y_test, y_pred))
        print(metrics.classification_report(y_test, y_pred))



####################
ovr   linear
[[11  0  0]
 [ 0  7  0]
 [ 0  0 12]]
Accuracy Score on confusion_matrix:  1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00        12

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

####################
ovo   linear
[[11  0  0]
 [ 0  7  0]
 [ 0  0 12]]
Accuracy Score on confusion_matrix:  1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00        12

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

##############

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using r